name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restaurar pacotes NuGet
      run: nuget restore Ripple.sln

    - name: Compilar solução
      run: msbuild Ripple.sln /p:Configuration=Release /p:Platform="Any CPU" /p:AllowUnsafeBlocks=true

    - name: Criar arquivo ZIP dos binários
      run: |
        mkdir build_artifacts
        Copy-Item -Path "Ripple\bin\Release\*" -Destination "build_artifacts" -Recurse
        Compress-Archive -Path "build_artifacts\*" -DestinationPath "build_artifacts.zip"

    - name: Fazer upload dos artefatos
      uses: actions/upload-artifact@v3
      with:
        name: Build-Artifacts
        path: build_artifacts.zip

  release:

    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Criar Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download dos artefatos
      uses: actions/download-artifact@v3
      with:
        name: Build-Artifacts

    - name: Fazer upload dos artefatos para o Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build_artifacts.zip
        asset_name: build_artifacts.zip
        asset_content_type: application/zip
        token: ${{ secrets.GITHUB_TOKEN }}
